mencoba kubernetes lagi

diff --git a/trigger-jenkins.yaml b/trigger-jenkins.yaml
--- a/trigger-jenkins.yaml
+++ b/trigger-jenkins.yaml
@@ -5,13 +5,17 @@ metadata:
 spec:
   containers:
     - name: jenkins-webhook
-      image: curlimages/curl:latest
-      command: ["/bin/sh", "-c"]
+      image: alpine:latest
+      command: ["/bin/sh"]
       args:
+        - "-c"
         - |
-          response_code=$(curl -v -k --user admin:11312a0a0096aac2316f158e26db6bee1a --max-time 10 -X POST -H 'cache-control: no-cache' -H 'content-type: application/x-www-form-urlencoded' --data 'IMAGE_TAG=latest' -o /dev/null -w "%{http_code}" http://10.2.62.221:18080/job/priajiservices/build?token=argocd-token)
-          if [ "$response_code" == "201" ]; then
+          wget --quiet --method=POST --timeout=10 --header='cache-control: no-cache' --header='content-type: application/x-www-form-urlencoded' --body-data='IMAGE_TAG=latest' --output-document=/dev/null http://10.2.62.221:18080/job/priajiservices/build?token=argocd-token
+          exit_code=$?
+          if [ $exit_code -eq 0 ]; then
             echo "HTTP 201 - Build completed successfully"
           else
-            echo "HTTP $response_code - Build failed or incomplete"
+            echo "Failed to access URL. Exit code: $exit_code"
+            exit $exit_code
           fi
+  restartPolicy: Never
